### ISSUE TITLE
C64 cart plugin does not work in recent binary ninjas

### ISSUE THREAD

**Issue by RevPanda** [Vector35/6502#5]
A plugin that used to work with (much) older BNs is spotty and produces heaps of backtraces in 4.1.5109-dev.

Trending towards user error in order of calling in the plugin or something, but I said in Slack there would be an issue, so here it is.

When I tried yesterday the cartridge dump didn't load at all and you ended up in raw view and there are a little over 100k lines of backtraces. When I tried today the backtraces are still there, but it loaded into a 6502 view with the plugins symbol creation all done. Doing the actions the plugin does manually in the console ends up with the correct result and no backtraces.

Example backtrace:
`
[0:140236877600128 Default info] Cart autoboot signature: CBM80
[16229809792511630840:12500298803194527301 BinaryView debug] Updating functions for uses of symbol at 0x8004
[0:12500298803194527301 Undo debug] Adding undo action without calling BeginUndoActions... This is suspicious. Action: Commented at 0x8004
[0:12500298803194527301 Undo debug] UNDO: Add action Commented at 0x8004 to entry 930e1908-8e48-4f22-9451-9165e3bbffdf
[0:12500298803194527301 Undo debug] UNDO: Commit 930e1908-8e48-4f22-9451-9165e3bbffdf
[0:12500298803194527301 Undo debug] UNDO: Commit entry 930e1908-8e48-4f22-9451-9165e3bbffdf
[0:140236877600128 Default info] cold reset vector: 0x8087
[0:140236877600128 Default info] warn reset vector: 0x8DE7
[16229809792511630840:12500298803194527301 BinaryView debug] Updating functions for uses of symbol at 0x8000
[16229809792511630840:12500298803194527301 BinaryView debug] Updating functions for uses of symbol at 0x8002
[16229809792511630840:12500298803194527301 BinaryView debug] Updating functions for uses of symbol at 0x8087
[0:12500298803194527301 Undo debug] Adding undo action without calling BeginUndoActions... This is suspicious. Action: Created function at 0x8087 for platform 6502
[0:12500298803194527301 Undo debug] UNDO: Add action Created function at 0x8087 for platform 6502 to entry cc9b0f2c-99c3-4299-9209-27a1a7e992bb
[0:12500298803194527301 Undo debug] UNDO: Commit cc9b0f2c-99c3-4299-9209-27a1a7e992bb
[0:12500298803194527301 Undo debug] UNDO: Commit entry cc9b0f2c-99c3-4299-9209-27a1a7e992bb
[16229809792511630840:12500298803194527301 Analysis debug] Added 6502 function at 0x8087
[16229809792511630840:12500298803194527301 Analysis debug] Starting analysis update
[0:140236877600128 Default error] Traceback (most recent call last):
  File "/home/username/hack/binaryninja/plugins/../python/binaryninja/binaryview.py", line 3204, in _get_address_size
    return self.perform_get_address_size()
  File "/home/username/hack/binaryninja/plugins/../python/binaryninja/binaryview.py", line 3295, in perform_get_address_size
    raise NotImplementedError
NotImplementedError
[0:140236877600128 Default error] Traceback (most recent call last):
  File "/home/username/hack/binaryninja/plugins/../python/binaryninja/binaryview.py", line 3204, in _get_address_size
    return self.perform_get_address_size()
  File "/home/username/hack/binaryninja/plugins/../python/binaryninja/binaryview.py", line 3295, in perform_get_address_size
    raise NotImplementedError
NotImplementedError
[16229809792511630840:12500298803194527301 BinaryView debug] Updating functions for uses of symbol at 0xa000
[0:140236877600128 Default error] Traceback (most recent call last):
  File "/home/username/hack/binaryninja/plugins/../python/binaryninja/binaryview.py", line 3204, in _get_address_size
...
`

The plugin DD001-ROM.py and example ROM can be found in https://github.com/RevPanda/bn-c64
Tests where done using v1.1 of the ROM.

The temptation to clean up the code before committing it was resisted because this is the code that used to work without problems once upon a time. Excuse the many, many warts but feel free to point them out.

**Comment by galenbwill** [comment]
The `BinaryView` class in the API has changed and now requires implementing this abstract method:
https://github.com/Vector35/binaryninja-api/blob/dev/python/binaryview.py#L3293-L3295

And I can confirm that adding this method to your `DD001View` class does make that error go away:
```python
    def perform_get_address_size(self) -> int:
        return 2
```

I am closing this issue as it is not an issue with Binary Ninja, just a change in the API that requires an update in the plugin.

**Comment by RevPanda** [comment]
This solves the problem. Many thanks!
